sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_install:
  - npm i -g typings commentator
  - typings install
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm run benchmark | commentator
  - npm run js-cpa | commentator
  - npm run coverage
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
